[report.ls]
filter = "type:todo status:active or type:event due.after:sod"
sort = ["due+", "created+"]
columns = [
  { field = "id", label = "ID", width = 4 },
  { field = "status", label = "ST", icon = true },
  { field = "date", label = "DATE", todo_format = "relative" },
  { field = "summary", label = "SUMMARY" },
]

[report.list]
filter = "type:todo -status:completed -status:cancelled or type:event due.after:sod"
sort = ["status-", "pri-", "due+"]
columns = [
  { field = "id", label = "ID", width = 4 },
  { field = "status", label = "STATUS", icon = true },
  { field = "pri", label = "PRI" },
  { field = "date", label = "DATE", todo_format = "relative" },
  { field = "tags", label = "TAGS" },
  { field = "summary", label = "SUMMARY" },
  { field = "desc", label = "DESC" },
]

[report.next]
filter = "type:todo status:active or type:event due.after:sod"
sort = ["due+", "pri-"]
columns = [
  { field = "id", label = "ID", width = 4 },
  { field = "status", label = "ST", icon = true },
  { field = "date", label = "DATE", todo_format = "relative" },
  { field = "summary", label = "SUMMARY" },
]
