[ui]
theme = "default"
vim_keys = true
default_filter = "all"

[theme]
name = "default"
"rule.precedence.color" = "deleted,completed,active,overdue,due.today,due,uda.,blocked,blocking,scheduled,tagged"

[theme.color]
deleted = "gray8 on gray1"
completed = "gray10 on gray2"
active = "underline"
overdue = "inverse"
"due.today" = "underline"
due = "bold"
blocked = "gray18"
"uda.priority.L" = "gray14"
"uda.priority.M" = "green"
"uda.priority.H" = "yellow"
blocking = "gray23"
scheduled = "gray22"
tagged = "gray21 bold"
